export const ADD_FILL = "ADD_FILL";
export const EDIT_FILL = "EDIT_FILL";
export const REMOVE_FILL = "REMOVE_FILL";
export const ADD_MAINTENANCE = "ADD_MAINTENANCE";
export const EDIT_MAINTENANCE = "EDIT_MAINTENANCE";
export const REMOVE_MAINTENANCE = "REMOVE_MAINTENANCE";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const SELECT_VEHICLE = "SELECT_VEHICLE";
